 export default{
	loginState:null,
	userName:null,
	captchaKey:null,
	captchaStr:null,
	heroData:{},//基础数据
	heroMatchData:null,//英雄比赛数据
	version:'',
	statusHealth:200,
	statusMana:75,
	statusHealthRegen:0.25,
	allTeamInfo:null,//所有战队的基础数据
	teamHeroPool:null,
	tenMinData:null,
	teamData:null,//战队数据
	matchDetails:null,
	lineUpRequest:null,
	lineUpDets:null,
	midUseHeroes:null,//中单选手某个英雄在比赛中的表现
	playerSameHero:null,//某个选手某个英雄在比赛中的表现
	sideLineUpData:null,
}